=== erizomovil/TareaLND/Systems.dtd
<!ELEMENT universe (galaxies*)>
<!ELEMENT galaxies (galaxy+)>
<!ELEMENT galaxy (gal:name,systems)>
<!ELEMENT gal:name (#PCDATA)>
<!ELEMENT systems (system+)>
<!ELEMENT system (sys:name,sys:structure,stars,planets)>
<!ELEMENT sys:name (#PCDATA)>
<!ELEMENT sys:structure (#PCDATA)>
<!ELEMENT stars (star+)>
<!ELEMENT star (sta:name,sta:type,sta:temperature)>
<!ELEMENT sta:name (#PCDATA)>
<!ELEMENT sta:type (#PCDATA)>
<!ELEMENT sta:temperature (#PCDATA)>
<!ELEMENT planets (planet+)>
<!ELEMENT planet (pla:name,pla:type,pla:temperature,habitable,native_species?,resources?)>
<!ELEMENT pla:name (#PCDATA)>
<!ELEMENT pla:type (#PCDATA)>
<!ELEMENT pla:temperature (#PCDATA)>
<!ELEMENT habitable (#PCDATA)>
<!ELEMENT native_species (specie+)>
<!ELEMENT specie (spe:name,is_inteligent,population,caracteristics,life_span)>
<!ELEMENT spe:name (#PCDATA)>
<!ELEMENT is_inteligent (#PCDATA)>
<!ELEMENT population (#PCDATA)>
<!ELEMENT caracteristics (#PCDATA)>
<!ELEMENT life_span (#PCDATA)>
<!ELEMENT resources (resource+)>
<!ELEMENT resource (res:name,res:type)>
<!ELEMENT res:name (#PCDATA)>
<!ELEMENT res:type (#PCDATA)>
<!ATTLIST galaxy galaxy_id CDATA #REQUIRED>
<!ATTLIST system system_id CDATA #REQUIRED>
<!ATTLIST star star_id CDATA #REQUIRED>
<!ATTLIST planet planet_id CDATA #REQUIRED>
<!ATTLIST specie specie_id CDATA #REQUIRED>
<!ATTLIST universe xmlns:gal CDATA #REQUIRED>
<!ATTLIST universe xmlns:sys CDATA #REQUIRED>
<!ATTLIST universe xmlns:sta CDATA #REQUIRED>
<!ATTLIST universe xmlns:pla CDATA #REQUIRED>
<!ATTLIST universe xmlns:spe CDATA #REQUIRED>
<!ATTLIST universe xmlns:res CDATA #REQUIRED>

=== erizomovil/TareaLND/Systems.xml
<!DOCTYPE universe SYSTEM "Systems.dtd">
<universe xmlns:gal="http://galaxy/html/" xmlns:sys="http://system/html/" xmlns:sta="http://star/html/" xmlns:pla="http://planet/html/" xmlns:spe="http://specie/html/" xmlns:res="http://resource/html/">
    <galaxies>
        <galaxy galaxy_id="1">
            <gal:name>Vía Láctea</gal:name>
            <systems>
                <system system_id="1">
                    <sys:name>sistema solar</sys:name>
                    <sys:structure>3 dimensiones</sys:structure>
                    <stars>
                        <star star_id="1">
                            <sta:name>sol</sta:name>
                            <sta:type>G2V</sta:type>
                            <sta:temperature>5772</sta:temperature>
                        </star>
                    </stars>
                    <planets>
                        <planet planet_id="1">
                            <pla:name>tierra</pla:name>
                            <pla:type>terrestre</pla:type>
                            <pla:temperature>30</pla:temperature>
                            <habitable>si</habitable>
                            <native_species>
                                <specie specie_id="1">
                                    <spe:name>homo sapien</spe:name>
                                    <is_inteligent>si</is_inteligent>
                                    <population>7888000000000</population>
                                    <caracteristics>bipedo</caracteristics>
                                    <life_span>80</life_span>
                                </specie>
                                <specie specie_id="2">
                                    <spe:name>Hydrochoerus hydrochaeris</spe:name>
                                    <is_inteligent>no</is_inteligent>
                                    <population>67983</population>
                                    <caracteristics>cuadrupedo</caracteristics>
                                    <life_span>12</life_span>
                                </specie>
                            </native_species>
                            <resources>
                                <resource>
                                    <res:name>hierro</res:name>
                                    <res:type>mineral</res:type>
                                </resource>
                                <resource>
                                    <res:name>madera</res:name>
                                    <res:type>planta</res:type>
                                </resource>
                            </resources>
                        </planet>
                        <planet planet_id="2">
                            <pla:name>neptuno</pla:name>
                            <pla:type>neptuniano</pla:type>
                            <pla:temperature>53</pla:temperature>
                            <habitable>no</habitable>
                            <resources>
                                <resource>
                                    <res:name>metano</res:name>
                                    <res:type>gas</res:type>
                                </resource>
                            </resources>
                        </planet>
                    </planets>
                </system>
                <system system_id="2">
                    <sys:name>sistema G432</sys:name>
                    <sys:structure>2 dimensiones</sys:structure>
                    <stars>
                        <star star_id="2">
                            <sta:name>Spica</sta:name>
                            <sta:type>G2V</sta:type>
                            <sta:temperature>6074</sta:temperature>
                        </star>
                    </stars>
                    <planets>
                        <planet planet_id="4">
                            <pla:name>CoRoT-18 b</pla:name>
                            <pla:type>joviano</pla:type>
                            <pla:temperature>1122,85</pla:temperature>
                            <habitable>no</habitable>
                        </planet>
                        <planet planet_id="5">
                            <pla:name>CoRoT-22 b</pla:name>
                            <pla:type>neptuniano</pla:type>
                            <pla:temperature>646,65 </pla:temperature>
                            <habitable>no</habitable>
                            <resources>
                                <resource>
                                    <res:name>metano</res:name>
                                    <res:type>gas</res:type>
                                </resource>
                            </resources>
                        </planet>
                    </planets>
                </system>
            </systems>
        </galaxy>
        <galaxy galaxy_id="2">
            <gal:name>Vía Láctea</gal:name>
            <systems>
                <system system_id="3">
                    <sys:name>sistema solar</sys:name>
                    <sys:structure>3 dimensiones</sys:structure>
                    <stars>
                        <star star_id="3">
                            <sta:name>antares</sta:name>
                            <sta:type>G2V</sta:type>
                            <sta:temperature>3409</sta:temperature>
                        </star>
                        <star star_id="4">
                            <sta:name>pollux</sta:name>
                            <sta:type>G2V</sta:type>
                            <sta:temperature>2304</sta:temperature>
                        </star>
                    </stars>
                    <planets>
                        <planet planet_id="6">
                            <pla:name>coruscant</pla:name>
                            <pla:type>terrestre</pla:type>
                            <pla:temperature>30</pla:temperature>
                            <habitable>si</habitable>
                            <native_species>
                                <specie specie_id="1">
                                    <spe:name>human</spe:name>
                                    <is_inteligent>si</is_inteligent>
                                    <population>1000000000000000</population>
                                    <caracteristics>bipedo</caracteristics>
                                    <life_span>300</life_span>
                                </specie>
                            </native_species>
                            <resources>
                                <resource>
                                    <res:name>hierro</res:name>
                                    <res:type>mineral</res:type>
                                </resource>
                                <resource>
                                    <res:name>implantes</res:name>
                                    <res:type>tecnologia</res:type>
                                </resource>
                                <resource>
                                    <res:name>creditos</res:name>
                                    <res:type>papel</res:type>
                                </resource>
                            </resources>
                        </planet>
                    </planets>
                </system>
            </systems>
        </galaxy>
    </galaxies>
</universe>
